---

inherit_gem:
  rubocop-fnando: .rubocop.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails

Metrics/AbcSize:
  Exclude:
    - db/**/*.rb
    - config/config.rb
    - test/support/**/*.rb

Metrics/BlockLength:
  Exclude:
    - config/config.rb
    - test/**/*.rb

Layout/LineLength:
  Exclude:
    - db/**/*.rb
    - config/environments/**/*.rb

Rails/Delegate:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false
