---

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space
  EnforcedStyleForEmptyBraces: space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: no_space

Lint/Debugger:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Enabled: true
  Max: 80

Metrics/MethodLength:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ModuleFunction:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%": "[]"
    "%i": "[]"
    "%q": "[]"
    "%Q": "[]"
    "%r": "{}"
    "%s": "[]"
    "%w": "[]"
    "%W": "[]"
    "%x": "[]"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Style/TrailingUnderscoreVariable:
  Enabled: false
