---

inherit_gem:
  rubocop-fnando: .rubocop.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-rails

Metrics/AbcSize:
  Exclude:
    - !ruby/regexp /^db\/.*?\.rb$/
    - !ruby/regexp /^config\/config\.rb$/
    - !ruby/regexp /^test\/support\/.*?\.rb$/

Metrics/BlockLength:
  Exclude:
    - !ruby/regexp /^config\/config\.rb$/
    - !ruby/regexp /^config\/routes\.rb$/
    - !ruby/regexp /^config\/routes\/.*?\.rb$/
    - !ruby/regexp /^test\/support\/factories\/.*?\.rb$/

Layout/LineLength:
  Exclude:
    - !ruby/regexp /^db\/.*?\.rb$/
    - !ruby/regexp /^config\/environments\/.*?\.rb$/

Rails/Delegate:
  Enabled: false

Rails/RefuteMethods:
  Enabled: false
